[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"
solana_version = "2.1.15"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
simple_escrow = "71axVYtoJyNVYVtJzVVcKEJLETtvenx2yJ89eMP1a2PK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/devnet/program-keypair.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.cjs"